[package]
name = "shoply-backend"
version = "0.1.0"
authors = ["Noah Hsu <xuhaojuntw@gmail.com>"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "service", "member-service", "entity", "migration"]

[dependencies]
shoply-api = { path = "api" }
