//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::{prelude::*, Set};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub images: Vec<String>,

    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ProductVariants,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ProductVariants => Entity::has_many(super::product_variant::Entity).into(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        let now = chrono::Utc::now();
        return Self {
            id: Set(Uuid::now_v7()),
            created_at: Set(now),
            updated_at: Set(now.clone()),
            ..ActiveModelTrait::default()
        };
    }
}
